### ISSUE TITLE
I18n is not working

### ISSUE THREAD

**Issue by stoicborg** [lunich/table_for#10]
I edit the locale file as
http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models
says, but table headers are still not translated

**Comment by Ptico** [comment]
Can you try in your rails console something like this:

``` ruby
YourModel.human_attribute_name(:your_attribute)
```

and make sure what it translates correctly?

**Comment by stoicborg** [comment]
I tried in the console and it's working correctly, but in the view it doesn't. 
I also double checked I18n.locale in the view, the locale is correct.
It's so weird.
