### ISSUE TITLE
custom tr #id

### ISSUE THREAD

**Issue by juliobetta** [lunich/table_for#5]
What if I want to put a different id attribute for each tr?

**Comment by Ptico** [comment]
I think i add this functionality in next version (after my vacation, sorry)

**Comment by juliobetta** [comment]
ok, tks!!!

**Comment by lunich** [comment]
fixed
now you can pass something like
:html => { :tr => { :id => lambda { |user| "user-row-#{user.id}" } } }
to table_for method

**Comment by juliobetta** [comment]
WOW!!!! thanks my friend!!! that's very handy!

On Wed, Nov 16, 2011 at 9:25 PM, Dima Lunich <
reply@reply.github.com

> wrote:
> 
> fixed
> now you can pass something like
> :html => { :tr => { :id => lambda { |user| "user-row-#{user.id}" } } }
> to table_for method
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lunich/table_for/issues/5#issuecomment-2769846

## 

JulioBêtta
Linux User #518828

**Comment by auxout** [comment]
how about class attribute?
